---
{{- if .Values.security.cluster.tls }}
{{- if .Values.autoscaling }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cert-master-autoscaler
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "cert-master"
  minReplicas: {{ .Values.certmaster.replicas.min }}
  maxReplicas: {{ .Values.certmaster.replicas.max }}
  targetCPUUtilizationPercentage: 90
{{- end}}
{{- end}}
