apiVersion: v2

name: argus
description: An automated security checking platform that is highly extensible.
home: https://github.com/WatcherWhale/SecProA
sources:
  - https://github.com/WatcherWhale/SecProA

type: application
version: 0.2.1

dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.8.5

  - name: autocert
    repository: https://smallstep.github.io/helm-charts/
    version: 1.16.3
    condition: security.cluster.tls

maintainers:
  - name: Mathias Maes
    url: https://github.com/WatcherWhale
  - name: Cato van Hooijdonk
    url: https://github.com/vanHooijdonkC
