---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gateway"
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app: "gateway"
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas.min }}
  selector:
    matchLabels:
      app: "gateway"
  template:
    metadata:
      annotations:
        {{- set .Values.gateway.podAnnotations "autocert.step.sm/name" "gateway-server" | toYaml | nindent 8 }}
      labels:
        app: "gateway"
    spec:
      tolerations:
        {{- toYaml .Values.gateway.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.gateway.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.gateway.nodeSelector | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.gateway.securityContext | nindent 8 }}
      containers:
        - name: "gateway"
          image: "{{ .Values.image.registry }}/gateway:{{ .Values.gateway.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "15Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "300m"
          env:
            # Web port
            - name: PORT
              value: "3000"

            # Redis settings
            - name: REDIS_HOST
              value: "{{ .Values.redis.fullnameOverride | default (printf "%s-redis" .Chart.Name ) }}"
            - name: REDIS_PORT
              value: "26379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.redis.fullnameOverride | default (printf "%s-redis" .Chart.Name ) }}"
                  key: redis-password

            - name: LOGLEVEL
              value: "{{ .Values.gateway.loglevel }}"

            {{- if .Values.security.cluster.tls}}

            - name: TLS_ENABLED
              value: "TRUE"
            - name: CERT_PATH
              value: "/var/run/autocert.step.sm/site.crt"
            - name: KEY_PATH
              value: "/var/run/autocert.step.sm/site.key"
            - name: CA_PATH
              value: "/var/run/autocert.step.sm/root.crt"

            {{- else }}

            - name: TLS_ENABLED
              value: "FALSE"

            {{- end}}
