---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "descriptions"
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app: "descriptions"
  annotations:
    {{- toYaml .Values.descriptions.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.descriptions.replicas.min }}
  selector:
    matchLabels:
      app: "descriptions"
  template:
    metadata:
      annotations:
        {{- set .Values.descriptions.podAnnotations "autocert.step.sm/name" "descriptions-server" | toYaml | nindent 8 }}
      labels:
        app: "descriptions"
    spec:
      tolerations:
        {{- toYaml .Values.descriptions.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.descriptions.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.descriptions.nodeSelector | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.descriptions.securityContext | nindent 8 }}
      containers:
        - name: "descriptions"
          image: "{{ .Values.image.registry }}/descriptions:{{ .Values.descriptions.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80
          resources: {}
